### ISSUE TITLE
[feat] Issue form template for new roadmap

### ISSUE THREAD

**Issue by CBID2** [roadmapsh/next.roadmap.sh#344]
Hi there! I think it would be beneficial to have an issue form template for the following categories:
1. New Roadmap 
2. Edit/Add to current roadmap 
3. Bug issue
4. Documentation issue

In my experience, having different templates for specific issues make a project more organized.

**Comment by kamranahmedse** [comment]
This has been done in the main repo. Thank you for the nudge!
