### ISSUE TITLE
[Rust Roadmap] Initial Submission for PR

### ISSUE THREAD

**Issue by joshua-mo-143** [roadmapsh/next.roadmap.sh#365]
Hey! I'd like to submit the following textual roadmap for the Rust roadmap.

- Roadmap until Language selection
- Basics
  - Basic Syntax
  - Variables & Declaration
  - Modules, imports
- Primitive Types
  - String and &str (string slice)
  - i8, i16, i32, i64
  - u8, u16, u32, u64
- Basic concepts
  - Conditionals
  - Functions
  - Type parsing
  - Type inference
  - Structs & Enums
  - Iterators
  - HashMaps
  - Vectors
- Build Your First Program
  - A Rust CLI
- Going Deeper
  - JSON (De)Serialization - Serde
  - Tokio
  - Implementations
  - Traits
  - Channels
- Web Frameworks
  - Actix-Web
  - Axum 
  - Rocket
- Logging
  - tracing
  - log
- Real time communication
  - tungstenite
  - tokio-tungstenite
- Non-rest HTTP Clients
  - async-graphql
  - Tonic (gRPC)
- Testing
- Deploying
  - Railway
  - Shuttle
  - Fly.io
- Backend roadmap after lang selection

**Comment by BlessingAbekah** [comment]
Thanks I will gradually follow to improve my coding

**Comment by SwannHERRERA** [comment]
Thank you for initiating this discussion. I've gone through the points you've mentioned and would like to suggest a few additions that could enrich the roadmap.

Firstly, it's essential to clarify that String is not a primitive type in Rust but I am according to you it's important to distinguish all the type related to the concept of string.
Additionally, topics such as lifetimes, move semantics (including borrowing and ownership), closures, and the concepts of references and immutability are pivotal in Rust and should not be overlooked.

Rust's approach to macros is unique and kind of scary at first, their absence in the current roadmap is quite noticeable.

I truly like some design pattern implementation in rust like Typestate Pattern it could be great to have a section on those.

Linking Rust's learning roadmap to blockchain roadmap could be interesting given the growing use of Rust in this domain. Drawing inspiration from the C++ roadmap for basic types and functions could serve as a solid framework for this.

Additionally, Rust's package manager and build system, cargo, deserves a point, and maybe some utils like cargo audit, miri, loom, clippy...

Rust is also very good for WebAssembly usage, we should mention it.

I believe these inclusions would offer a well-rounded and practical approach to mastering Rust.

Looking forward to further discussion and collaboration on this.

**Comment by joshua-mo-143** [comment]
Closed. It looks like a Rust roadmap was already made.
